version: '3'
services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    flask:
        image: antonisr11/swarm-flask
        restart: always
        networks:
            - proxy
        ports:
            - 5000:5000
